### PR TITLE
Solved #3 fetch data using Spotify API

### PR DESCRIPTION
**Pull request by Abhijeet-2003**
I have successfully fetched the _Artists, Albums, Tracks, Playlists, Recently Played Tracks, User Devices, Recommended Tracks and User Information_ using the **Spotify API**. I've also created an appropriate UI for all the fetched data.
Playing the songs, playlists or albums is not possible as it requires the user to have **Spotify PREMIUM**.

There are a few things to keep in mind for anyone who is going to work further on this project.

1. Firstly, you need to get a **Client ID** and a **Client Secret**. For that, you'll have to go to [https://developer.spotify.com/](url), log in and go to the dashboard, then click on 'Create an App' and fill in the necessary details.
2. You'll see a page with your **Client ID** and a **Client Secret**. On the same page, you need to click on "_Users and Access_" and enter the required details. After doing this, click on "_Edit Settings_" and add a **Redirect URI** which should be the **_same_** as the URI of "_index.html_". In my case, it was "http://127.0.0.1:5500". Similarly, in "_app.js- Line 7_" and in "_auth.js- Line 1_" modify the **var redirect_uri**.
3. After doing all this, you can now run "_auth.html_". Fill in the required details. If it shows "_Invalid Redirect URI_", please verify whether the **Redirect URI** you entered previously are correct and matching with each other. If everything is right, you'll see a Spotify Authorization page.
4. After you click on "Agree", you'll be redirected to "_index.html_". Refresh the page once or maybe twice and you'll get your tracks, albums, artists, user information, etc. If there's any error, try to refresh the Spotify developer page and index.html too.

### CODE REVIEW

**Comment by Abhijeet-2003** [comment]
Screenshot 2022-12-26 at 1 14 58 PM

**Comment by Abhijeet-2003** [comment]
Screenshot 2022-12-26 at 1 15 07 PM

**Comment by Abhijeet-2003** [comment]
Screenshot 2022-12-26 at 1 15 14 PM

**Comment by Abhijeet-2003** [comment]
Screenshot 2022-12-26 at 1 17 15 PM

**Comment by boradesanket13** [comment]
Great job, @Abhijeet-2003 . Really nice implementation. 🚀
But this branch has conflicts that must be resolved. It will be great if you fix that and make another PR. ✔

**Comment by Abhijeet-2003** [comment]
@boradesanket13 . I would suggest creating a new branch for this PR as the music can't be played in this. Hence, there would be no conflicts and merging would be possible

**Pull request closed without merging**
